version: '3'

services:

 web:
    image: nginx:stable-alpine
    container_name: webserver
    ports:
        - "8080:80"
    volumes:
        - ./www:/var/www/html
        - ./site.conf:/etc/nginx/conf.d/site.conf
    privileged: true

 php:
    build: ./
    image: "php-fpm"
    container_name: php71fpm
    volumes:
        - ./www:/var/www/html
    privileged: true
